Add dark mode endpoint and grouping by route direction
CUMTD/Mtd.Kiosk.Api pull request #8
Opened 2024-08-28 16:00 UTC by mattnovelli

2024-08-28 16:52 UTC, rblackman requested changes
A few suggestions and cleanups.

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +	[ProducesResponseType(StatusCodes.Status404NotFound)]
It doesn't look like this will actually produce a 400 or 404.

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +
```suggestion
```

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +		ZonedDateTime zonedDateTime = SystemClock.Instance.GetCurrentInstant().InZone(zone);
```suggestion
		var zonedDateTime = SystemClock.Instance.GetCurrentInstant().InZone(zone);
```

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +		DateTimeZone zone = DateTimeZoneProviders.Tzdb["America/Chicago"];
```suggestion
		var zone = DateTimeZoneProviders.Tzdb["America/Chicago"];
```

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +		DateTime utcDateTime = zonedDateTime.ToDateTimeUtc();
```suggestion
		var utcDateTime = zonedDateTime.ToDateTimeUtc();
```

2024-08-28 16:52 UTC, rblackman commented on Mtd.Kiosk.Api/Controllers/TimeController.cs
> +		return Ok(!sunUp);
Even though we're only returning one value, I recommend returning an object here rather than a raw value. Something like:

```csharp
public class DarkModePayload
{
   public required boolean SunIsUp { get; set; }
}
````

2024-08-29 20:27 UTC, mattnovelli reviewed
cool code

2024-08-29 20:30 UTC, merged